# Generated by Django 4.1.7 on 2023-04-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='comision',
        ),
    ]
